import = [
  # light themes
  # "~/.config/alacritty/themes/themes/noctis-lux.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
  # "~/.config/alacritty/themes/themes/github_light.toml"
  # dark themes
  # "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
  # "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
  # "~/.config/alacritty/themes/themes/nord.toml"
  # "~/.config/alacritty/themes/themes/oceanic_next.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
	# "~/.config/alacritty/themes/themes/catppuccin.toml"
]

# [colors.primary]
# foreground = "#FFFFFF"

[env]
TERM = "xterm-256color"

[font]
size = 12
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
bold.style = "Bold"

[selection]
save_to_clipboard = true

[window]
# decorations = "None"
padding.x = 2
padding.y = 2
opacity = 0.8
blur = true

# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["new-session", "-A", "-s", "main"]

